# QC-large four-model comparison

This notebook focuses on the QC-large strict-left dataset because it is the only dataset in this repo
that contains the exact four-model comparison:

- BrainODE PCA150
- PCA150 cocycle flow
- SIREN cocycle flow
- SIREN latent ODE

The figures stay on the current evaluated outputs and only decode new meshes when you explicitly run
the anchor forecast cells.

In [1]:
from pathlib import Path
import importlib
import sys

import pandas as pd
from IPython.display import Markdown, display

root = Path.cwd().resolve()
while not (root / ".git").exists():
    if root.parent == root:
        raise RuntimeError("Could not locate repo root from current working directory.")
    root = root.parent

script_dir = root / "examples" / "ADNI_1_L_No_MCI" / "brainode_comparison_task3_core_brainode_original" / "scripts"
if str(script_dir) not in sys.path:
    sys.path.insert(0, str(script_dir))

import longitudinal_visual_notebook_support as lv
lv = importlib.reload(lv)

ctx = lv.create_context(device="auto")
display(Markdown(
    "Using `longitudinal_visual_notebook_support.py`. "
    "Observed-pair plots are light. Anchor forecast cells decode meshes for the SIREN models and run best on CUDA."
))

Using `longitudinal_visual_notebook_support.py`. Observed-pair plots are light. Anchor forecast cells decode meshes for the SIREN models and run best on CUDA.

## Ground-truth CN vs AD aging

Relative change is measured from each subject's baseline scan. The shaded band is the interquartile range
across subjects with at least two scans.

In [2]:
display(Markdown(
    "### Ground-truth relative aging curves\n"
    "- **Input:** all QC-large ground-truth scan volumes in `train`, `val`, and `test`.\n"
    "- **Output:** mean relative hippocampus volume change from each subject's own baseline, shown separately for `CN` and `AD`.\n"
    "- **Calculation:** for each subject, `relative change = 100 * (current volume - baseline volume) / baseline volume`."
))
fig = ctx.plot_ground_truth_cn_ad_aging()
fig.show()
display(Markdown(
    "After this graph: more negative values indicate stronger volume loss from baseline. "
    "Because the axis is baseline-relative, subjects with different absolute hippocampus sizes are directly comparable."
))

display(Markdown(
    "### Ground-truth annualized start-to-end change\n"
    "- **Input:** the first and last observed scan for each subject.\n"
    "- **Output:** subject-level annualized percent volume change, grouped by split and diagnosis.\n"
    "- **Calculation:** `(last - first) / first / follow-up years`."
))
fig = ctx.plot_ground_truth_start_end_rates()
fig.show()
display(Markdown(
    "After this graph: this is a compact endpoint summary. "
    "The previous curve uses all observed visits, while this box plot uses only the first and last scan per subject."
))

### Ground-truth relative aging curves
- **Input:** all QC-large ground-truth scan volumes in `train`, `val`, and `test`.
- **Output:** mean relative hippocampus volume change from each subject's own baseline, shown separately for `CN` and `AD`.
- **Calculation:** for each subject, `relative change = 100 * (current volume - baseline volume) / baseline volume`.

After this graph: more negative values indicate stronger volume loss from baseline. Because the axis is baseline-relative, subjects with different absolute hippocampus sizes are directly comparable.

### Ground-truth annualized start-to-end change
- **Input:** the first and last observed scan for each subject.
- **Output:** subject-level annualized percent volume change, grouped by split and diagnosis.
- **Calculation:** `(last - first) / first / follow-up years`.

After this graph: this is a compact endpoint summary. The previous curve uses all observed visits, while this box plot uses only the first and last scan per subject.

## Future-pair reconstruction metrics

These are mesh metrics on observed future pairs. Distances stay in millimeters.
Volume quantities are displayed in cubic centimeters and surface-area quantities in square centimeters
so the magnitudes read like hippocampus-scale anatomy instead of raw millimeter powers.

In [3]:
display(Markdown(
    "### Observed future-pair reconstruction error\n"
    "- **Input:** observed source-to-future scan pairs shared by the four comparison models.\n"
    "- **Models:** BrainODE PCA150, PCA150 cocycle flow, SIREN cocycle flow, and SIREN latent ODE.\n"
    "- **Output:** geometric and anatomical endpoint errors after forecasting the future shape. Distances stay in `mm`; volume and surface-area errors are shown in `cm^3` and `cm^2`."
))
fig = ctx.plot_reconstruction_metric_grid()
fig.show()

summary = ctx.model_pair_summary().sort_values(["model_label", "transport_label"]).reset_index(drop=True)
display(summary)
display(Markdown(
    "After this graph: lower bars are better. "
    "ASSD and HD95 summarize surface mismatch; the volume and surface-area panels summarize endpoint anatomy error."
))

### Observed future-pair reconstruction error
- **Input:** observed source-to-future scan pairs shared by the four comparison models.
- **Models:** BrainODE PCA150, PCA150 cocycle flow, SIREN cocycle flow, and SIREN latent ODE.
- **Output:** geometric and anatomical endpoint errors after forecasting the future shape. Distances stay in `mm`; volume and surface-area errors are shown in `cm^3` and `cm^2`.

,model,model_label,transport_method,transport_label,rows,assd_mm,hd95_mm,volume_abs_error_cm3,surface_area_abs_error_cm2,volume_relative_error_pct,surface_area_relative_error_pct
0,qc_brainode_pca150,BrainODE PCA150,brainode_endpoint,endpoint,616,0.397266,0.953809,0.148665,0.532132,5.244451,3.413010
1,pca150_direct_cocycle_flow,PCA150 cocycle flow,composed_observed,composed,4685,0.366449,0.870374,0.135633,0.459840,4.541547,2.872185
2,pca150_direct_cocycle_flow,PCA150 cocycle flow,direct,direct,4685,0.366632,0.868658,0.134613,0.463901,4.460371,2.882153
3,qc_siren_drop_bad_min2,SIREN cocycle flow,composed,composed,616,0.524387,1.190346,0.165503,1.183031,5.824892,7.578552
4,qc_siren_drop_bad_min2,SIREN cocycle flow,direct,direct,616,0.523028,1.188655,0.164847,1.139687,5.799675,7.307718
5,qc_siren_latent_ode,SIREN latent ODE,composed,composed,616,0.519465,1.182097,0.169911,1.158225,5.971341,7.654797
6,qc_siren_latent_ode,SIREN latent ODE,direct,direct,616,0.519391,1.181976,0.169914,1.158108,5.971451,7.654050

After this graph: lower bars are better. ASSD and HD95 summarize surface mismatch; the volume and surface-area panels summarize endpoint anatomy error.

## Cached train/val/test model volume trends

This section uses already-computed observed-age trend tables only when they already exist in the repo.
If a model has no matching cached QC-large split-wide trend table, it is intentionally omitted here.

In [4]:
trend_models = ctx.available_cached_split_trend_models()
if not trend_models:
    display(Markdown("No cached split-wide QC-large model trend tables were found for notebook 1."))
else:
    display(Markdown(
        "The next figures use existing rows from `selected_volume_trends.csv`. "
        "They are not recomputed inside this notebook."
    ))
    for model in trend_models:
        summary = ctx.cached_split_volume_trend_summary(model)
        transport_label = summary["transport"].iloc[0] if not summary.empty else "cached transport"
        display(Markdown(
            f"### {lv.MODEL_LABELS[model]} split-wise CN vs AD trend\n"
            f"- **Input:** cached QC-large observed-age trend rows for `{lv.MODEL_LABELS[model]}`.\n"
            f"- **Transport used:** `{transport_label}`.\n"
            "- **Output:** mean relative volume change from baseline across subjects, separated by split and diagnosis.\n"
            "- **Calculation:** both the observed and predicted curves are normalized by the subject's observed baseline volume."
        ))
        fig = ctx.plot_cached_split_volume_trends(model)
        fig.show()
        display(summary)
        display(Markdown(
            "After this graph: solid lines are observed ground-truth trends and dashed lines are model-predicted trends on the same baseline-relative scale."
        ))

The next figures use existing rows from `selected_volume_trends.csv`. They are not recomputed inside this notebook.

### PCA150 cocycle flow split-wise CN vs AD trend
- **Input:** cached QC-large observed-age trend rows for `PCA150 cocycle flow`.
- **Transport used:** `direct from baseline`.
- **Output:** mean relative volume change from baseline across subjects, separated by split and diagnosis.
- **Calculation:** both the observed and predicted curves are normalized by the subject's observed baseline volume.

,model,transport,split,diagnosis,subjects,scans,median_followup_years,max_followup_years
0,PCA150 cocycle flow,direct from baseline,train,CN,25,236,3.117043,10.255989
1,PCA150 cocycle flow,direct from baseline,train,AD,25,101,0.958244,2.992470
2,PCA150 cocycle flow,direct from baseline,val,CN,25,146,1.330597,10.017792
3,PCA150 cocycle flow,direct from baseline,val,AD,24,72,0.505135,2.072556
4,PCA150 cocycle flow,direct from baseline,test,AD,21,65,0.517452,2.140999
5,PCA150 cocycle flow,direct from baseline,test,CN,25,141,1.245720,10.195763

After this graph: solid lines are observed ground-truth trends and dashed lines are model-predicted trends on the same baseline-relative scale.

### SIREN cocycle flow split-wise CN vs AD trend
- **Input:** cached QC-large observed-age trend rows for `SIREN cocycle flow`.
- **Transport used:** `direct from baseline`.
- **Output:** mean relative volume change from baseline across subjects, separated by split and diagnosis.
- **Calculation:** both the observed and predicted curves are normalized by the subject's observed baseline volume.

,model,transport,split,diagnosis,subjects,scans,median_followup_years,max_followup_years
0,SIREN cocycle flow,direct from baseline,train,AD,13,53,0.960986,2.992471
1,SIREN cocycle flow,direct from baseline,train,CN,13,124,3.990418,10.255989
2,SIREN cocycle flow,direct from baseline,val,CN,15,110,2.027379,10.017796
3,SIREN cocycle flow,direct from baseline,val,AD,15,52,0.532512,2.072553
4,SIREN cocycle flow,direct from baseline,test,AD,15,53,0.517454,2.140999
5,SIREN cocycle flow,direct from baseline,test,CN,15,103,2.061602,10.195756

After this graph: solid lines are observed ground-truth trends and dashed lines are model-predicted trends on the same baseline-relative scale.

## Instantaneous latent velocity

This section evaluates the local latent vector field at every observed scan. It does not decode meshes.

For cocycle flow models, the displayed velocity is the diagonal generator:

`G(z, t, t, c) / age_range_years`

For ODE models, the displayed velocity is the ODE vector field:

`f(z, t, c) / age_range_years`

The observed reference velocity is estimated from neighboring real scans in the same latent space.
PCA and SIREN latent speeds are not compared as raw units; the main plots use train-standardized
latent speed so each model is judged against its own representation scale.

In [5]:
display(Markdown(
    "### Build or load instantaneous velocity cache\n"
    "- **Input:** all train/val/test observed scan latents for BrainODE PCA150, PCA150 cocycle flow, SIREN cocycle flow, and SIREN latent ODE.\n"
    "- **Output:** per-scan instantaneous model velocity, observed scan-to-scan latent velocity, model-vs-real error, and CN-vs-AD condition gap.\n"
    "- **Calculation:** no mesh is generated. The cache is reused on later notebook runs unless the support script version changes."
))
velocity_tables = ctx.build_instantaneous_velocity_tables()
display(velocity_tables["summary"].head(18))
display(Markdown(
    f"Loaded `{len(velocity_tables['per_scan'])}` per-scan/condition velocity rows and "
    f"`{len(velocity_tables['condition_gap'])}` CN-vs-AD condition-gap rows."
))

display(Markdown(
    "### Model velocity magnitude vs real local velocity\n"
    "- **Input:** observed-condition rows only.\n"
    "- **Output:** bars show the model's median instantaneous latent speed; `x` markers show the median real scan-to-scan latent speed.\n"
    "- **Calculation:** speeds are divided by the training latent standard deviation component-by-component, then summarized as an L2 norm per year."
))
fig = ctx.plot_instantaneous_velocity_model_vs_real()
fig.show()
display(Markdown(
    "After this graph: if a model bar is far below the real marker for AD, the model is underestimating AD progression speed even if its future meshes look plausible."
))

display(Markdown(
    "### Velocity error and direction agreement\n"
    "- **Input:** observed-condition rows only.\n"
    "- **Output:** top row = median train-standardized velocity error; bottom row = median cosine similarity between model velocity and observed local velocity.\n"
    "- **Calculation:** cosine near `1` means the model moves in the same latent direction as the observed scan-to-scan change; near `0` means weak directional agreement."
))
fig = ctx.plot_instantaneous_velocity_alignment()
fig.show()
display(Markdown(
    "After this graph: this separates speed magnitude from direction. A model can have plausible speed but still move in the wrong latent direction."
))

display(Markdown(
    "### CN-vs-AD instantaneous condition gap\n"
    "- **Input:** the same source scan evaluated twice: once with CN condition and once with AD condition.\n"
    "- **Output:** `AD-conditioned speed - CN-conditioned speed`, grouped by source diagnosis and split.\n"
    "- **Calculation:** positive values mean the AD condition makes the instantaneous vector field faster than the CN condition for the same scan."
))
fig = ctx.plot_instantaneous_velocity_condition_gap()
fig.show()
display(ctx.instantaneous_velocity_condition_gap_summary())
display(Markdown(
    "After this graph: this is the direct local test of whether the condition label changes the velocity field in the expected disease direction."
))

display(Markdown(
    "### Velocity by age bin\n"
    "- **Input:** observed-condition rows only.\n"
    "- **Output:** median instantaneous model speed and median observed local speed by age bin, separated by CN and AD.\n"
    "- **Calculation:** this checks whether the learned vector field changes with age rather than only with diagnosis."
))
fig = ctx.plot_instantaneous_velocity_age_trend()
fig.show()
display(Markdown(
    "After this graph: a clinically useful disease-aging model should show both age-dependent behavior and stronger AD velocity than CN where the real data shows that pattern."
))

### Build or load instantaneous velocity cache
- **Input:** all train/val/test observed scan latents for BrainODE PCA150, PCA150 cocycle flow, SIREN cocycle flow, and SIREN latent ODE.
- **Output:** per-scan instantaneous model velocity, observed scan-to-scan latent velocity, model-vs-real error, and CN-vs-AD condition gap.
- **Calculation:** no mesh is generated. The cache is reused on later notebook runs unless the support script version changes.

,dataset,model,model_label,model_priority,latent_family,generator_kind,split,diagnosis,condition_eval,rows,...,model_velocity_z_l2_median,velocity_l2_error_mean,velocity_l2_error_median,velocity_z_l2_error_mean,velocity_z_l2_error_median,velocity_cosine_mean,velocity_cosine_median,model_to_real_speed_ratio_median,split_priority,condition_priority
0,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,AD,observed,496,...,0.292383,2.045445,1.817796,17.281141,14.665344,0.154445,0.164972,0.050795,0,0
1,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,AD,CN,496,...,0.273100,2.046175,1.819147,17.280924,14.667375,0.154053,0.165100,0.047043,0,1
2,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,AD,AD,496,...,0.352013,2.043767,1.813253,17.282120,14.660766,0.154980,0.164128,0.060131,0,2
3,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,AD,observed,496,...,0.975715,2.046149,1.834415,17.254508,14.749336,0.118377,0.160087,0.080377,0,0
4,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,AD,CN,496,...,0.926795,2.055132,1.831418,17.259705,14.742296,0.057969,0.104590,0.071536,0,1
5,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,AD,AD,496,...,0.975715,2.046149,1.834415,17.254508,14.749336,0.118377,0.160087,0.080377,0,2
6,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,train,AD,observed,496,...,2.276088,1.349831,1.102713,25.284421,20.709735,-0.000038,-0.000238,0.109170,0,0
7,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,train,AD,CN,496,...,1.450282,1.345745,1.098314,25.209900,20.629322,-0.000298,-0.001005,0.065816,0,1
8,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,train,AD,AD,496,...,2.276088,1.349831,1.102713,25.284421,20.709735,-0.000038,-0.000238,0.109170,0,2
9,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,train,AD,observed,496,...,8.316171,1.430597,1.185882,26.768481,22.176803,-0.000177,-0.002183,0.401074,0,0
10,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,train,AD,CN,496,...,4.031027,1.365231,1.118150,25.567653,20.920367,-0.000468,-0.002182,0.184295,0,1
11,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,train,AD,AD,496,...,8.316171,1.430597,1.185882,26.768481,22.176803,-0.000177,-0.002183,0.401074,0,2
12,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,CN,observed,1295,...,0.288928,1.130968,0.923564,10.757291,8.883517,0.097032,0.102489,0.098848,0,0
13,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,CN,CN,1295,...,0.269360,1.130915,0.924513,10.756994,8.886680,0.097041,0.101796,0.091396,0,1
14,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,CN,AD,1295,...,0.348502,1.131337,0.927363,10.758722,8.875880,0.096910,0.103061,0.117139,0,2
15,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,CN,observed,1295,...,0.966338,1.130156,0.924726,10.746427,8.889734,0.105789,0.136284,0.137531,0,0
16,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,CN,CN,1295,...,0.966338,1.130156,0.924726,10.746427,8.889734,0.105789,0.136284,0.137531,0,1
17,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,CN,AD,1295,...,1.040282,1.130187,0.931305,10.752871,8.862109,0.119170,0.148635,0.173073,0,2

Loaded `26748` per-scan/condition velocity rows and `8916` CN-vs-AD condition-gap rows.

### Model velocity magnitude vs real local velocity
- **Input:** observed-condition rows only.
- **Output:** bars show the model's median instantaneous latent speed; `x` markers show the median real scan-to-scan latent speed.
- **Calculation:** speeds are divided by the training latent standard deviation component-by-component, then summarized as an L2 norm per year.

After this graph: if a model bar is far below the real marker for AD, the model is underestimating AD progression speed even if its future meshes look plausible.

### Velocity error and direction agreement
- **Input:** observed-condition rows only.
- **Output:** top row = median train-standardized velocity error; bottom row = median cosine similarity between model velocity and observed local velocity.
- **Calculation:** cosine near `1` means the model moves in the same latent direction as the observed scan-to-scan change; near `0` means weak directional agreement.

After this graph: this separates speed magnitude from direction. A model can have plausible speed but still move in the wrong latent direction.

### CN-vs-AD instantaneous condition gap
- **Input:** the same source scan evaluated twice: once with CN condition and once with AD condition.
- **Output:** `AD-conditioned speed - CN-conditioned speed`, grouped by source diagnosis and split.
- **Calculation:** positive values mean the AD condition makes the instantaneous vector field faster than the CN condition for the same scan.

,dataset,model,model_label,model_priority,latent_family,generator_kind,split,diagnosis,rows,subjects,scans,ad_minus_cn_velocity_z_mean,ad_minus_cn_velocity_z_median,ad_minus_cn_velocity_l2_mean,ad_minus_cn_velocity_l2_median,ad_over_cn_velocity_z_ratio_median,split_priority
0,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,AD,496,160,496,0.078904,0.078907,0.023773,0.023774,1.288967,0
1,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,AD,496,160,496,0.030728,0.027794,0.014682,0.014294,1.029370,0
2,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,train,AD,496,160,496,0.825529,0.826462,0.044644,0.044694,1.569620,0
3,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,train,AD,496,160,496,4.267363,4.275165,0.230134,0.230512,2.064842,0
4,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,train,CN,1295,261,1295,0.079127,0.079142,0.023777,0.023778,1.293807,0
5,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,train,CN,1295,261,1295,0.070553,0.070827,0.031860,0.034228,1.073552,0
6,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,train,CN,1295,261,1295,0.823409,0.823228,0.044532,0.044521,1.589751,0
7,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,train,CN,1295,261,1295,4.240378,4.239316,0.228677,0.228619,2.163669,0
8,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,val,AD,72,24,72,0.078948,0.078970,0.023774,0.023774,1.290276,1
9,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,val,AD,72,24,72,0.036493,0.036268,0.017338,0.021366,1.040002,1
10,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,val,AD,72,24,72,0.824131,0.826115,0.044574,0.044674,1.596560,1
11,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,val,AD,72,24,72,4.244163,4.237731,0.228915,0.228482,2.094182,1
12,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,val,CN,152,28,152,0.079113,0.079133,0.023777,0.023778,1.293920,1
13,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,val,CN,152,28,152,0.061100,0.061770,0.026952,0.027299,1.051712,1
14,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,val,CN,152,28,152,0.825776,0.825452,0.044657,0.044628,1.586903,1
15,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,val,CN,152,28,152,4.268529,4.267329,0.230184,0.230109,2.113223,1
16,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,test,AD,65,21,65,0.078892,0.078888,0.023773,0.023773,1.288598,2
17,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,test,AD,65,21,65,0.042963,0.038413,0.015146,0.009967,1.038243,2
18,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,test,AD,65,21,65,0.828037,0.828325,0.044778,0.044780,1.545864,2
19,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,test,AD,65,21,65,4.289833,4.298079,0.231333,0.231729,2.013015,2
20,qc_large,qc_brainode_pca150,BrainODE PCA150,0,pca150,ode_vector_field,test,CN,149,29,149,0.079095,0.079099,0.023777,0.023777,1.293113,2
21,qc_large,pca150_direct_cocycle_flow,PCA150 cocycle flow,1,pca150,cocycle_diagonal_generator,test,CN,149,29,149,0.061183,0.056497,0.026337,0.028203,1.058723,2
22,qc_large,qc_siren_drop_bad_min2,SIREN cocycle flow,2,siren256,cocycle_diagonal_generator,test,CN,149,29,149,0.824818,0.824549,0.044604,0.044579,1.585490,2
23,qc_large,qc_siren_latent_ode,SIREN latent ODE,3,siren256,ode_vector_field,test,CN,149,29,149,4.286548,4.287294,0.231147,0.231222,2.060066,2

After this graph: this is the direct local test of whether the condition label changes the velocity field in the expected disease direction.

### Velocity by age bin
- **Input:** observed-condition rows only.
- **Output:** median instantaneous model speed and median observed local speed by age bin, separated by CN and AD.
- **Calculation:** this checks whether the learned vector field changes with age rather than only with diagnosis.

After this graph: a clinically useful disease-aging model should show both age-dependent behavior and stronger AD velocity than CN where the real data shows that pattern.

## Representative observed-pair cases

Cases are chosen split-by-split and diagnosis-by-diagnosis from pairs that exist for all four models.
Preference is given to longer gaps, then lower average future-pair error.

In [6]:
cases = ctx.representative_cases()
case_table = pd.DataFrame(
    [
        {
            "split": case.split,
            "diagnosis": case.diagnosis,
            "subject_id": case.subject_id,
            "source_scan_id": case.source_scan_id,
            "target_scan_id": case.target_scan_id,
        }
        for case in cases
    ]
)
display(case_table)
display(Markdown(
    "Each row defines one source-to-target case used below. "
    "The first case-study section shows only the selected target prediction per model; the next case-study section expands that into predictions at each observed follow-up age between source and target."
))

   split diagnosis subject_id source_scan_id target_scan_id
0  train        CN         31     31_bl_left   31_m120_left
1  train        AD        995    995_bl_left   995_m36_left
2    val        CN        677    677_bl_left  677_m120_left
3    val        AD        850    850_bl_left   850_m24_left
4   test        CN        113    113_bl_left  113_m108_left
5   test        AD       1339   1339_bl_left  1339_m24_left

Each row defines one source-to-target case used below. The first case-study section shows only the selected target prediction per model; the next case-study section expands that into predictions at each observed follow-up age between source and target.

## Volume history around the selected future-pair cases

Each panel shows the real subject trajectory and the model-predicted target volume at the selected future age.
Volumes are displayed in cubic centimeters.

In [7]:
for case in cases:
    display(Markdown(f"### {case.split.upper()} {case.diagnosis} | subject {case.subject_id}"))
    display(ctx.case_overview_table(case))
    display(Markdown(
        "- **Input:** the full observed subject history plus the selected source-to-target pair for this case.\n"
        "- **Output:** black line = all observed scan volumes for the subject; colored diamonds = each model's prediction only at the selected target age.\n"
        "- **Important:** intermediate observed ages before the target are shown only on the black ground-truth line in this plot."
    ))
    fig = ctx.plot_case_subject_history(case)
    fig.show()
    display(Markdown(
        "After this graph: this is a target-only endpoint comparison. "
        "The next section fills in the missing intermediate predictions before the target."
    ))

### TRAIN CN | subject 31

,model,chosen_transport,gap_years,chamfer_l2_squared,assd_mm,hd95_mm,volume_abs_error_cm3,surface_area_abs_error_cm2
0,BrainODE PCA150,endpoint,10.255989,0.002070,0.540511,1.487205,0.559828,1.883015
1,PCA150 cocycle flow,composed,10.255989,0.000857,0.376803,0.988132,0.062958,0.054143
2,SIREN cocycle flow,direct,10.255988,0.002718,0.675967,1.649827,0.535662,5.268731
3,SIREN latent ODE,direct,10.255988,0.003244,0.775844,1.719510,0.515956,1.458915

- **Input:** the full observed subject history plus the selected source-to-target pair for this case.
- **Output:** black line = all observed scan volumes for the subject; colored diamonds = each model's prediction only at the selected target age.
- **Important:** intermediate observed ages before the target are shown only on the black ground-truth line in this plot.

After this graph: this is a target-only endpoint comparison. The next section fills in the missing intermediate predictions before the target.

### TRAIN AD | subject 995

,model,chosen_transport,gap_years,chamfer_l2_squared,assd_mm,hd95_mm,volume_abs_error_cm3,surface_area_abs_error_cm2
0,BrainODE PCA150,endpoint,2.99247,0.001964,0.567999,1.555335,0.433917,1.458598
1,PCA150 cocycle flow,direct,2.99247,0.001568,0.523069,1.376177,0.394957,1.272675
2,SIREN cocycle flow,direct,2.99247,0.002392,0.670843,1.417985,0.400495,1.797953
3,SIREN latent ODE,composed,2.99247,0.002087,0.614934,1.361651,0.179811,3.784340

- **Input:** the full observed subject history plus the selected source-to-target pair for this case.
- **Output:** black line = all observed scan volumes for the subject; colored diamonds = each model's prediction only at the selected target age.
- **Important:** intermediate observed ages before the target are shown only on the black ground-truth line in this plot.

After this graph: this is a target-only endpoint comparison. The next section fills in the missing intermediate predictions before the target.

### VAL CN | subject 677

,model,chosen_transport,gap_years,chamfer_l2_squared,assd_mm,hd95_mm,volume_abs_error_cm3,surface_area_abs_error_cm2
0,BrainODE PCA150,endpoint,10.017792,0.000930,0.407103,0.979004,0.011041,0.209210
1,PCA150 cocycle flow,composed,10.017792,0.000868,0.399677,1.014496,0.194782,0.782563
2,SIREN cocycle flow,direct,10.017795,0.001545,0.520756,1.351631,0.342225,5.186007
3,SIREN latent ODE,composed,10.017795,0.001278,0.483083,1.189915,0.475163,2.044264

- **Input:** the full observed subject history plus the selected source-to-target pair for this case.
- **Output:** black line = all observed scan volumes for the subject; colored diamonds = each model's prediction only at the selected target age.
- **Important:** intermediate observed ages before the target are shown only on the black ground-truth line in this plot.

After this graph: this is a target-only endpoint comparison. The next section fills in the missing intermediate predictions before the target.

### VAL AD | subject 850

,model,chosen_transport,gap_years,chamfer_l2_squared,assd_mm,hd95_mm,volume_abs_error_cm3,surface_area_abs_error_cm2
0,BrainODE PCA150,endpoint,2.072556,0.001144,0.433299,1.148457,0.224740,0.449097
1,PCA150 cocycle flow,direct,2.072556,0.001135,0.423489,1.177752,0.257954,0.556010
2,SIREN cocycle flow,composed,2.072554,0.002182,0.630565,1.563062,0.345804,0.913411
3,SIREN latent ODE,direct,2.072554,0.002609,0.693818,1.585796,0.203367,3.772449

- **Input:** the full observed subject history plus the selected source-to-target pair for this case.
- **Output:** black line = all observed scan volumes for the subject; colored diamonds = each model's prediction only at the selected target age.
- **Important:** intermediate observed ages before the target are shown only on the black ground-truth line in this plot.

After this graph: this is a target-only endpoint comparison. The next section fills in the missing intermediate predictions before the target.

### TEST CN | subject 113

,model,chosen_transport,gap_years,chamfer_l2_squared,assd_mm,hd95_mm,volume_abs_error_cm3,surface_area_abs_error_cm2
0,BrainODE PCA150,endpoint,10.195763,0.001276,0.468012,1.170911,0.082402,0.253927
1,PCA150 cocycle flow,composed,10.195763,0.001364,0.485011,1.283798,0.259457,0.666698
2,SIREN cocycle flow,composed,10.195756,0.001273,0.467661,1.207466,0.020633,3.886926
3,SIREN latent ODE,composed,10.195756,0.001245,0.466477,1.168507,0.229147,2.531866

- **Input:** the full observed subject history plus the selected source-to-target pair for this case.
- **Output:** black line = all observed scan volumes for the subject; colored diamonds = each model's prediction only at the selected target age.
- **Important:** intermediate observed ages before the target are shown only on the black ground-truth line in this plot.

After this graph: this is a target-only endpoint comparison. The next section fills in the missing intermediate predictions before the target.

### TEST AD | subject 1339

,model,chosen_transport,gap_years,chamfer_l2_squared,assd_mm,hd95_mm,volume_abs_error_cm3,surface_area_abs_error_cm2
0,BrainODE PCA150,endpoint,2.140999,0.001244,0.471948,1.157105,0.229941,0.276845
1,PCA150 cocycle flow,direct,2.140999,0.001185,0.462451,1.133379,0.238488,0.271595
2,SIREN cocycle flow,direct,2.141001,0.001329,0.513087,1.128257,0.318092,0.895384
3,SIREN latent ODE,composed,2.141001,0.001373,0.509474,1.174647,0.226899,3.334334

- **Input:** the full observed subject history plus the selected source-to-target pair for this case.
- **Output:** black line = all observed scan volumes for the subject; colored diamonds = each model's prediction only at the selected target age.
- **Important:** intermediate observed ages before the target are shown only on the black ground-truth line in this plot.

After this graph: this is a target-only endpoint comparison. The next section fills in the missing intermediate predictions before the target.

## Per-model predictions at every observed follow-up age between source and target

This section addresses the gap in the simpler history plots above: if a subject has observed follow-up scans
before the selected target, each model is now evaluated at those observed ages as well, using the same source scan as input.

In [8]:
for case in cases:
    display(Markdown(f"## {case.split.upper()} {case.diagnosis} | subject {case.subject_id} | source-to-observed follow-up forecasts"))
    for model in ctx.available_models():
        fig, table = ctx.plot_case_model_followup_forecast(case, model)
        first = table.iloc[0]
        transport_label = str(table['transport_label'].dropna().iloc[0]) if table['transport_label'].notna().any() else 'endpoint'
        display(Markdown(
            f"### {lv.MODEL_LABELS[model]}\n"
            f"- **Input:** source scan `{first['source_scan_id']}` at age `{first['source_age_years']:.2f}` years with diagnosis `{first['diagnosis']}`.\n"
            f"- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `{first['target_age_years']:.2f}`.\n"
            f"- **Transport / mode:** `{transport_label}`.\n"
            "- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh."
        ))
        fig.show()
        display(table)
        ok = table.loc[table['status'].astype(str).eq('ok') & table['predicted_volume_cm3'].notna()].copy()
        mae = float(ok['abs_error_cm3'].mean()) if not ok.empty else float('nan')
        skipped = int(table['status'].astype(str).ne('ok').sum())
        display(Markdown(
            f"After this graph: mean absolute error across the shown observed follow-up ages is `{mae:.3f} cm^3` "
            f"for the successful predictions. Skipped ages due to failed mesh decode: `{skipped}`."
        ))

## TRAIN CN | subject 31 | source-to-observed follow-up forecasts

### BrainODE PCA150
- **Input:** source scan `31_bl_left` at age `77.70` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `87.96`.
- **Transport / mode:** `endpoint`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_bl_left,77.700000,False,3.725230,3.726255,0.001024,ok,NaN
1,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m06_left,78.181862,False,3.842658,3.714657,0.128001,ok,NaN
2,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m12_left,78.715743,False,4.128782,3.701755,0.427027,ok,NaN
3,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m24_left,79.756126,False,3.372957,3.676459,0.303503,ok,NaN
4,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m36_left,80.807461,False,3.501588,3.650694,0.149106,ok,NaN
5,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m48_left,81.694524,False,3.532291,3.628797,0.096506,ok,NaN
6,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m60_left,82.803354,False,3.402475,3.601226,0.198752,ok,NaN
7,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m72_left,83.687680,False,3.529717,3.579082,0.049364,ok,NaN
8,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m84_left,84.599384,False,3.364198,3.556109,0.191910,ok,NaN
9,train,CN,31,BrainODE PCA150,endpoint,31_bl_left,77.699997,31_m120_left,87.955986,31_m96_left,85.680835,False,3.346060,3.528673,0.182613,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.173 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### PCA150 cocycle flow
- **Input:** source scan `31_bl_left` at age `77.70` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `87.96`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_bl_left,77.700000,False,3.725230,3.726255,0.001024,ok,NaN
1,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m06_left,78.181862,False,3.842658,3.713142,0.129516,ok,NaN
2,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m12_left,78.715743,False,4.128782,3.695151,0.433631,ok,NaN
3,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m24_left,79.756126,False,3.372957,3.650597,0.277640,ok,NaN
4,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m36_left,80.807461,False,3.501588,3.594339,0.092751,ok,NaN
5,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m48_left,81.694524,False,3.532291,3.539179,0.006889,ok,NaN
6,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m60_left,82.803354,False,3.402475,3.462356,0.059882,ok,NaN
7,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m72_left,83.687680,False,3.529717,3.395381,0.134336,ok,NaN
8,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m84_left,84.599384,False,3.364198,3.322455,0.041744,ok,NaN
9,train,CN,31,PCA150 cocycle flow,composed,31_bl_left,77.699997,31_m120_left,87.955986,31_m96_left,85.680835,False,3.346060,3.231143,0.114918,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.129 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN cocycle flow
- **Input:** source scan `31_bl_left` at age `77.70` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `87.96`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_bl_left,77.700000,False,3.725230,3.725029,0.000202,ok,NaN
1,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m06_left,78.181862,False,3.842658,3.727992,0.114666,ok,NaN
2,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m12_left,78.715743,False,4.128782,3.731966,0.396816,ok,NaN
3,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m24_left,79.756126,False,3.372957,3.739353,0.366396,ok,NaN
4,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m36_left,80.807461,False,3.501588,3.743915,0.242327,ok,NaN
5,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m48_left,81.694524,False,3.532291,3.739440,0.207149,ok,NaN
6,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m60_left,82.803354,False,3.402475,3.717506,0.315031,ok,NaN
7,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m72_left,83.687680,False,3.529717,3.686028,0.156310,ok,NaN
8,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m84_left,84.599384,False,3.364198,3.644065,0.279867,ok,NaN
9,train,CN,31,SIREN cocycle flow,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m96_left,85.680835,False,3.346060,3.587554,0.241493,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.232 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN latent ODE
- **Input:** source scan `31_bl_left` at age `77.70` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `87.96`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_bl_left,77.700000,False,3.725230,3.725029,0.000202,ok,NaN
1,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m06_left,78.181862,False,3.842658,3.733545,0.109113,ok,NaN
2,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m12_left,78.715743,False,4.128782,3.738512,0.390270,ok,NaN
3,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m24_left,79.756126,False,3.372957,3.731248,0.358291,ok,NaN
4,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m36_left,80.807461,False,3.501588,3.705491,0.203903,ok,NaN
5,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m48_left,81.694524,False,3.532291,3.675011,0.142720,ok,NaN
6,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m60_left,82.803354,False,3.402475,3.631316,0.228841,ok,NaN
7,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m72_left,83.687680,False,3.529717,3.595304,0.065587,ok,NaN
8,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m84_left,84.599384,False,3.364198,3.557708,0.193510,ok,NaN
9,train,CN,31,SIREN latent ODE,direct,31_bl_left,77.699997,31_m120_left,87.955986,31_m96_left,85.680835,False,3.346060,3.512928,0.166867,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.186 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

## TRAIN AD | subject 995 | source-to-observed follow-up forecasts

### BrainODE PCA150
- **Input:** source scan `995_bl_left` at age `78.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.49`.
- **Transport / mode:** `endpoint`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,AD,995,BrainODE PCA150,endpoint,995_bl_left,78.5,995_m36_left,81.49247,995_bl_left,78.500000,False,2.182497,2.182830,0.000333,ok,NaN
1,train,AD,995,BrainODE PCA150,endpoint,995_bl_left,78.5,995_m36_left,81.49247,995_m06_left,78.984600,False,2.004142,2.168814,0.164671,ok,NaN
2,train,AD,995,BrainODE PCA150,endpoint,995_bl_left,78.5,995_m36_left,81.49247,995_m12_left,79.515743,False,1.820185,2.153469,0.333284,ok,NaN
3,train,AD,995,BrainODE PCA150,endpoint,995_bl_left,78.5,995_m36_left,81.49247,995_m24_left,80.734086,False,1.736623,2.118343,0.381720,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.220 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### PCA150 cocycle flow
- **Input:** source scan `995_bl_left` at age `78.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.49`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,AD,995,PCA150 cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_bl_left,78.500000,False,2.182497,2.182830,0.000333,ok,NaN
1,train,AD,995,PCA150 cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_m06_left,78.984600,False,2.004142,2.167579,0.163437,ok,NaN
2,train,AD,995,PCA150 cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_m12_left,79.515743,False,1.820185,2.148670,0.328485,ok,NaN
3,train,AD,995,PCA150 cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_m24_left,80.734086,False,1.736623,2.096443,0.359820,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.213 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN cocycle flow
- **Input:** source scan `995_bl_left` at age `78.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.49`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,AD,995,SIREN cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_bl_left,78.500000,False,2.182497,2.163443,0.019054,ok,NaN
1,train,AD,995,SIREN cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_m06_left,78.984600,False,2.004142,2.152353,0.148211,ok,NaN
2,train,AD,995,SIREN cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_m12_left,79.515743,False,1.820185,2.137546,0.317361,ok,NaN
3,train,AD,995,SIREN cocycle flow,direct,995_bl_left,78.5,995_m36_left,81.49247,995_m24_left,80.734086,False,1.736623,2.097665,0.361042,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.211 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN latent ODE
- **Input:** source scan `995_bl_left` at age `78.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.49`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,train,AD,995,SIREN latent ODE,composed,995_bl_left,78.5,995_m36_left,81.49247,995_bl_left,78.500000,False,2.182497,2.163443,0.019054,ok,NaN
1,train,AD,995,SIREN latent ODE,composed,995_bl_left,78.5,995_m36_left,81.49247,995_m06_left,78.984600,False,2.004142,2.157417,0.153275,ok,NaN
2,train,AD,995,SIREN latent ODE,composed,995_bl_left,78.5,995_m36_left,81.49247,995_m12_left,79.515743,False,1.820185,2.134556,0.314371,ok,NaN
3,train,AD,995,SIREN latent ODE,composed,995_bl_left,78.5,995_m36_left,81.49247,995_m24_left,80.734086,False,1.736623,1.969214,0.232591,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.180 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

## VAL CN | subject 677 | source-to-observed follow-up forecasts

### BrainODE PCA150
- **Input:** source scan `677_bl_left` at age `70.80` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.82`.
- **Transport / mode:** `endpoint`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,CN,677,BrainODE PCA150,endpoint,677_bl_left,70.800003,677_m120_left,80.817795,677_m06_left,71.374949,False,4.258986,4.291847,0.032861,ok,NaN
1,val,CN,677,BrainODE PCA150,endpoint,677_bl_left,70.800003,677_m120_left,80.817795,677_m12_left,71.796578,False,4.345957,4.271809,0.074147,ok,NaN
2,val,CN,677,BrainODE PCA150,endpoint,677_bl_left,70.800003,677_m120_left,80.817795,677_m24_left,72.899932,False,4.123782,4.219518,0.095735,ok,NaN
3,val,CN,677,BrainODE PCA150,endpoint,677_bl_left,70.800003,677_m120_left,80.817795,677_m48_left,74.843806,False,3.964574,4.127891,0.163316,ok,NaN
4,val,CN,677,BrainODE PCA150,endpoint,677_bl_left,70.800003,677_m120_left,80.817795,677_m60_left,76.004654,False,3.807831,4.073473,0.265642,ok,NaN
5,val,CN,677,BrainODE PCA150,endpoint,677_bl_left,70.800003,677_m120_left,80.817795,677_m72_left,77.001232,False,3.863884,4.026934,0.163050,ok,NaN
6,val,CN,677,BrainODE PCA150,endpoint,677_bl_left,70.800003,677_m120_left,80.817795,677_m84_left,78.016975,False,3.938970,3.979668,0.040698,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.119 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### PCA150 cocycle flow
- **Input:** source scan `677_bl_left` at age `70.80` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.82`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,CN,677,PCA150 cocycle flow,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m06_left,71.374949,False,4.258986,4.322384,0.063398,ok,NaN
1,val,CN,677,PCA150 cocycle flow,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m12_left,71.796578,False,4.345957,4.323183,0.022773,ok,NaN
2,val,CN,677,PCA150 cocycle flow,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m24_left,72.899932,False,4.123782,4.320018,0.196236,ok,NaN
3,val,CN,677,PCA150 cocycle flow,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m48_left,74.843806,False,3.964574,4.295972,0.331397,ok,NaN
4,val,CN,677,PCA150 cocycle flow,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m60_left,76.004654,False,3.807831,4.271560,0.463729,ok,NaN
5,val,CN,677,PCA150 cocycle flow,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m72_left,77.001232,False,3.863884,4.244952,0.381068,ok,NaN
6,val,CN,677,PCA150 cocycle flow,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m84_left,78.016975,False,3.938970,4.212974,0.274003,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.248 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN cocycle flow
- **Input:** source scan `677_bl_left` at age `70.80` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.82`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,CN,677,SIREN cocycle flow,direct,677_bl_left,70.800003,677_m120_left,80.817795,677_m06_left,71.374949,False,4.258986,4.314911,0.055925,ok,NaN
1,val,CN,677,SIREN cocycle flow,direct,677_bl_left,70.800003,677_m120_left,80.817795,677_m12_left,71.796578,False,4.345957,4.319286,0.026670,ok,NaN
2,val,CN,677,SIREN cocycle flow,direct,677_bl_left,70.800003,677_m120_left,80.817795,677_m24_left,72.899932,False,4.123782,4.327637,0.203855,ok,NaN
3,val,CN,677,SIREN cocycle flow,direct,677_bl_left,70.800003,677_m120_left,80.817795,677_m48_left,74.843806,False,3.964574,4.331914,0.367340,ok,NaN
4,val,CN,677,SIREN cocycle flow,direct,677_bl_left,70.800003,677_m120_left,80.817795,677_m60_left,76.004654,False,3.807831,4.326565,0.518734,ok,NaN
5,val,CN,677,SIREN cocycle flow,direct,677_bl_left,70.800003,677_m120_left,80.817795,677_m72_left,77.001232,False,3.863884,4.318810,0.454926,ok,NaN
6,val,CN,677,SIREN cocycle flow,direct,677_bl_left,70.800003,677_m120_left,80.817795,677_m84_left,78.016975,False,3.938970,4.302267,0.363297,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.284 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN latent ODE
- **Input:** source scan `677_bl_left` at age `70.80` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.82`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,CN,677,SIREN latent ODE,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m06_left,71.374949,False,4.258986,4.331600,0.072614,ok,NaN
1,val,CN,677,SIREN latent ODE,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m12_left,71.796578,False,4.345957,4.343259,0.002698,ok,NaN
2,val,CN,677,SIREN latent ODE,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m24_left,72.899932,False,4.123782,4.360901,0.237119,ok,NaN
3,val,CN,677,SIREN latent ODE,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m48_left,74.843806,False,3.964574,4.369451,0.404877,ok,NaN
4,val,CN,677,SIREN latent ODE,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m60_left,76.004654,False,3.807831,4.366601,0.558769,ok,NaN
5,val,CN,677,SIREN latent ODE,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m72_left,77.001232,False,3.863884,4.361125,0.497241,ok,NaN
6,val,CN,677,SIREN latent ODE,composed,677_bl_left,70.800003,677_m120_left,80.817795,677_m84_left,78.016975,False,3.938970,4.353800,0.414830,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.313 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

## VAL AD | subject 850 | source-to-observed follow-up forecasts

### BrainODE PCA150
- **Input:** source scan `850_bl_left` at age `78.10` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.17`.
- **Transport / mode:** `endpoint`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,AD,850,BrainODE PCA150,endpoint,850_bl_left,78.099998,850_m24_left,80.172554,850_bl_left,78.100000,False,2.226081,2.230415,0.004334,ok,NaN
1,val,AD,850,BrainODE PCA150,endpoint,850_bl_left,78.099998,850_m24_left,80.172554,850_m06_left,78.595551,False,2.190430,2.208717,0.018287,ok,NaN
2,val,AD,850,BrainODE PCA150,endpoint,850_bl_left,78.099998,850_m24_left,80.172554,850_m12_left,79.099316,False,2.012913,2.186717,0.173803,ok,NaN
3,val,AD,850,BrainODE PCA150,endpoint,850_bl_left,78.099998,850_m24_left,80.172554,850_m24_left,80.172553,True,1.915298,2.140037,0.224740,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.105 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### PCA150 cocycle flow
- **Input:** source scan `850_bl_left` at age `78.10` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.17`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,AD,850,PCA150 cocycle flow,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_bl_left,78.100000,False,2.226081,2.230415,0.004334,ok,NaN
1,val,AD,850,PCA150 cocycle flow,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_m06_left,78.595551,False,2.190430,2.219617,0.029187,ok,NaN
2,val,AD,850,PCA150 cocycle flow,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_m12_left,79.099316,False,2.012913,2.206821,0.193908,ok,NaN
3,val,AD,850,PCA150 cocycle flow,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_m24_left,80.172553,True,1.915298,2.173251,0.257954,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.121 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN cocycle flow
- **Input:** source scan `850_bl_left` at age `78.10` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.17`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,AD,850,SIREN cocycle flow,composed,850_bl_left,78.099998,850_m24_left,80.172554,850_bl_left,78.100000,False,2.226081,2.224143,0.001938,ok,NaN
1,val,AD,850,SIREN cocycle flow,composed,850_bl_left,78.099998,850_m24_left,80.172554,850_m06_left,78.595551,False,2.190430,2.235554,0.045124,ok,NaN
2,val,AD,850,SIREN cocycle flow,composed,850_bl_left,78.099998,850_m24_left,80.172554,850_m12_left,79.099316,False,2.012913,2.247610,0.234697,ok,NaN
3,val,AD,850,SIREN cocycle flow,composed,850_bl_left,78.099998,850_m24_left,80.172554,850_m24_left,80.172553,True,1.915298,2.253708,0.338410,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.155 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN latent ODE
- **Input:** source scan `850_bl_left` at age `78.10` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `80.17`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,val,AD,850,SIREN latent ODE,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_bl_left,78.100000,False,2.226081,2.224144,0.001937,ok,NaN
1,val,AD,850,SIREN latent ODE,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_m06_left,78.595551,False,2.190430,2.286590,0.096160,ok,NaN
2,val,AD,850,SIREN latent ODE,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_m12_left,79.099316,False,2.012913,2.282695,0.269782,ok,NaN
3,val,AD,850,SIREN latent ODE,direct,850_bl_left,78.099998,850_m24_left,80.172554,850_m24_left,80.172553,True,1.915298,2.109061,0.193764,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.140 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

## TEST CN | subject 113 | source-to-observed follow-up forecasts

### BrainODE PCA150
- **Input:** source scan `113_bl_left` at age `75.20` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `85.40`.
- **Transport / mode:** `endpoint`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_bl_left,75.200000,False,2.830897,2.830417,0.000480,ok,NaN
1,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m06_left,75.698289,False,2.909638,2.813413,0.096226,ok,NaN
2,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m12_left,76.191102,False,2.931493,2.796601,0.134892,ok,NaN
3,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m24_left,77.206845,False,2.869765,2.761971,0.107794,ok,NaN
4,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m48_left,79.265708,False,2.927265,2.691859,0.235407,ok,NaN
5,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m60_left,80.182888,False,2.841196,2.660663,0.180533,ok,NaN
6,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m72_left,81.182204,False,2.869308,2.626701,0.242607,ok,NaN
7,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m84_left,82.173306,False,2.877112,2.593048,0.284064,ok,NaN
8,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m96_left,83.169884,False,2.645668,2.559239,0.086429,ok,NaN
9,test,CN,113,BrainODE PCA150,endpoint,113_bl_left,75.199997,113_m108_left,85.39576,113_m108_left,85.395756,True,2.566245,2.483843,0.082402,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.145 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### PCA150 cocycle flow
- **Input:** source scan `113_bl_left` at age `75.20` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `85.40`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_bl_left,75.200000,False,2.830897,2.830417,0.000480,ok,NaN
1,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m06_left,75.698289,False,2.909638,2.837504,0.072134,ok,NaN
2,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m12_left,76.191102,False,2.931493,2.843910,0.087583,ok,NaN
3,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m24_left,77.206845,False,2.869765,2.855182,0.014583,ok,NaN
4,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m48_left,79.265708,False,2.927265,2.870180,0.057086,ok,NaN
5,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m60_left,80.182888,False,2.841196,2.873360,0.032165,ok,NaN
6,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m72_left,81.182204,False,2.869308,2.874476,0.005168,ok,NaN
7,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m84_left,82.173306,False,2.877112,2.873118,0.003994,ok,NaN
8,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m96_left,83.169884,False,2.645668,2.869273,0.223606,ok,NaN
9,test,CN,113,PCA150 cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m108_left,85.395756,True,2.566245,2.851967,0.285723,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.078 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN cocycle flow
- **Input:** source scan `113_bl_left` at age `75.20` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `85.40`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_bl_left,75.200000,False,2.830897,2.825140,0.005757,ok,NaN
1,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m06_left,75.698289,False,2.909638,2.825520,0.084119,ok,NaN
2,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m12_left,76.191102,False,2.931493,2.825081,0.106411,ok,NaN
3,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m24_left,77.206845,False,2.869765,2.821699,0.048066,ok,NaN
4,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m48_left,79.265708,False,2.927265,2.798814,0.128451,ok,NaN
5,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m60_left,80.182888,False,2.841196,2.779369,0.061826,ok,NaN
6,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m72_left,81.182204,False,2.869308,2.745494,0.123814,ok,NaN
7,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m84_left,82.173306,False,2.877112,2.703339,0.173773,ok,NaN
8,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m96_left,83.169884,False,2.645668,2.655353,0.009685,ok,NaN
9,test,CN,113,SIREN cocycle flow,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m108_left,85.395756,True,2.566245,2.534311,0.031933,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.077 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN latent ODE
- **Input:** source scan `113_bl_left` at age `75.20` years with diagnosis `CN`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `85.40`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_bl_left,75.200000,False,2.830897,2.825140,0.005757,ok,NaN
1,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m06_left,75.698289,False,2.909638,2.836264,0.073375,ok,NaN
2,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m12_left,76.191102,False,2.931493,2.843126,0.088367,ok,NaN
3,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m24_left,77.206845,False,2.869765,2.849023,0.020742,ok,NaN
4,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m48_left,79.265708,False,2.927265,2.838862,0.088404,ok,NaN
5,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m60_left,80.182888,False,2.841196,2.831120,0.010076,ok,NaN
6,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m72_left,81.182204,False,2.869308,2.824088,0.045220,ok,NaN
7,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m84_left,82.173306,False,2.877112,2.815335,0.061777,ok,NaN
8,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m96_left,83.169884,False,2.645668,2.806464,0.160796,ok,NaN
9,test,CN,113,SIREN latent ODE,composed,113_bl_left,75.199997,113_m108_left,85.39576,113_m108_left,85.395756,True,2.566245,2.789832,0.223587,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.078 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

## TEST AD | subject 1339 | source-to-observed follow-up forecasts

### BrainODE PCA150
- **Input:** source scan `1339_bl_left` at age `79.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.64`.
- **Transport / mode:** `endpoint`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,AD,1339,BrainODE PCA150,endpoint,1339_bl_left,79.5,1339_m24_left,81.640999,1339_bl_left,79.500000,False,2.133729,2.132936,0.000792,ok,NaN
1,test,AD,1339,BrainODE PCA150,endpoint,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m06_left,80.039357,False,1.981510,2.117424,0.135915,ok,NaN
2,test,AD,1339,BrainODE PCA150,endpoint,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m12_left,80.567762,False,2.137270,2.102243,0.035027,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.057 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### PCA150 cocycle flow
- **Input:** source scan `1339_bl_left` at age `79.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.64`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,AD,1339,PCA150 cocycle flow,direct,1339_bl_left,79.5,1339_m24_left,81.640999,1339_bl_left,79.500000,False,2.133729,2.132936,0.000792,ok,NaN
1,test,AD,1339,PCA150 cocycle flow,direct,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m06_left,80.039357,False,1.981510,2.122838,0.141328,ok,NaN
2,test,AD,1339,PCA150 cocycle flow,direct,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m12_left,80.567762,False,2.137270,2.110864,0.026406,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.056 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN cocycle flow
- **Input:** source scan `1339_bl_left` at age `79.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.64`.
- **Transport / mode:** `direct`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,AD,1339,SIREN cocycle flow,direct,1339_bl_left,79.5,1339_m24_left,81.640999,1339_bl_left,79.500000,False,2.133729,2.129237,0.004492,ok,NaN
1,test,AD,1339,SIREN cocycle flow,direct,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m06_left,80.039357,False,1.981510,2.138708,0.157199,ok,NaN
2,test,AD,1339,SIREN cocycle flow,direct,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m12_left,80.567762,False,2.137270,2.148430,0.011160,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.058 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

### SIREN latent ODE
- **Input:** source scan `1339_bl_left` at age `79.50` years with diagnosis `AD`.
- **Output:** predicted hippocampus volume at each observed follow-up age from the source age up to the selected target age `81.64`.
- **Transport / mode:** `composed`.
- **Calculation:** ground truth uses the physical mesh volume when available; the model curve uses the volume of the decoded forecast mesh.

,split,diagnosis,subject_id,model_label,transport_label,source_scan_id,source_age_years,target_scan_id,target_age_years,future_scan_id,future_age_years,is_target_scan,ground_truth_volume_cm3,predicted_volume_cm3,abs_error_cm3,status,error
0,test,AD,1339,SIREN latent ODE,composed,1339_bl_left,79.5,1339_m24_left,81.640999,1339_bl_left,79.500000,False,2.133729,2.129237,0.004492,ok,NaN
1,test,AD,1339,SIREN latent ODE,composed,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m06_left,80.039357,False,1.981510,2.190362,0.208853,ok,NaN
2,test,AD,1339,SIREN latent ODE,composed,1339_bl_left,79.5,1339_m24_left,81.640999,1339_m12_left,80.567762,False,2.137270,2.192824,0.055554,ok,NaN

After this graph: mean absolute error across the shown observed follow-up ages is `0.090 cm^3` for the successful predictions. Skipped ages due to failed mesh decode: `0`.

## Conditioned future volume forecasts from a single shape

These forecasts start from the first observed scan of the selected anchor subject.
Solid lines use the CN condition. Dashed lines use the AD condition.
Larger markers indicate prediction points at the exact observed follow-up ages for that subject.
The grey region begins after the last observed scan for the chosen anchor subject.
Volumes are displayed in cubic centimeters.

In [9]:
display(Markdown(
    "### Test CN anchor forecast\n"
    "- **Input:** one CN source scan from the test split, used as a fixed starting shape.\n"
    "- **Output:** future predicted volume under both the `CN` and `AD` condition labels.\n"
    "- **Calculation:** black is observed truth; solid colored lines are CN-conditioned forecasts; dashed colored lines are AD-conditioned forecasts."
))
fig = ctx.plot_anchor_forecasts(split="test", diagnosis="CN", transport="direct")
fig.show()
display(Markdown(
    "After this graph: the difference between the solid and dashed curves shows how much the diagnosis condition changes the future rollout while the source anatomy stays fixed."
))

display(Markdown(
    "### Test AD anchor forecast\n"
    "- **Input:** one AD source scan from the test split, used as a fixed starting shape.\n"
    "- **Output:** future predicted volume under both the `AD` and `CN` condition labels.\n"
    "- **Calculation:** the same source shape is rolled forward to observed and out-of-distribution ages, with the grey region starting after the subject's last observed scan."
))
fig = ctx.plot_anchor_forecasts(split="test", diagnosis="AD", transport="direct")
fig.show()
display(Markdown(
    "After this graph: this is a conditioning sensitivity test. "
    "It does not prove disentanglement, but it does show the direction and size of the label-dependent forecast change."
))

### Test CN anchor forecast
- **Input:** one CN source scan from the test split, used as a fixed starting shape.
- **Output:** future predicted volume under both the `CN` and `AD` condition labels.
- **Calculation:** black is observed truth; solid colored lines are CN-conditioned forecasts; dashed colored lines are AD-conditioned forecasts.

After this graph: the difference between the solid and dashed curves shows how much the diagnosis condition changes the future rollout while the source anatomy stays fixed.

### Test AD anchor forecast
- **Input:** one AD source scan from the test split, used as a fixed starting shape.
- **Output:** future predicted volume under both the `AD` and `CN` condition labels.
- **Calculation:** the same source shape is rolled forward to observed and out-of-distribution ages, with the grey region starting after the subject's last observed scan.

After this graph: this is a conditioning sensitivity test. It does not prove disentanglement, but it does show the direction and size of the label-dependent forecast change.

## Disease-conditioned gap

This is not disentanglement. It is the forecast separation induced by swapping the conditioning label
while keeping the source shape fixed.
Volume gaps are displayed in cubic centimeters.

In [10]:
display(Markdown(
    "### Test CN anchor disease-conditioned gap\n"
    "- **Input:** the CN anchor forecast from the previous section.\n"
    "- **Output:** `AD-conditioned predicted volume - CN-conditioned predicted volume` at each future age.\n"
    "- **Calculation:** each point subtracts two forecasts made from the same source shape."
))
fig = ctx.plot_anchor_condition_gap(split="test", diagnosis="CN", transport="direct")
fig.show()
display(Markdown(
    "After this graph: values below zero mean the AD-conditioned rollout predicts a smaller hippocampus than the CN-conditioned rollout."
))

display(Markdown(
    "### Test AD anchor disease-conditioned gap\n"
    "- **Input:** the AD anchor forecast from the previous section.\n"
    "- **Output:** the same `AD - CN` conditional gap, now starting from an AD source shape.\n"
    "- **Calculation:** the source scan is fixed and only the condition label is swapped."
))
fig = ctx.plot_anchor_condition_gap(split="test", diagnosis="AD", transport="direct")
fig.show()
display(Markdown(
    "After this graph: this quantifies label sensitivity on a shared source shape, rather than measuring reconstruction against ground truth."
))

### Test CN anchor disease-conditioned gap
- **Input:** the CN anchor forecast from the previous section.
- **Output:** `AD-conditioned predicted volume - CN-conditioned predicted volume` at each future age.
- **Calculation:** each point subtracts two forecasts made from the same source shape.

After this graph: values below zero mean the AD-conditioned rollout predicts a smaller hippocampus than the CN-conditioned rollout.

### Test AD anchor disease-conditioned gap
- **Input:** the AD anchor forecast from the previous section.
- **Output:** the same `AD - CN` conditional gap, now starting from an AD source shape.
- **Calculation:** the source scan is fixed and only the condition label is swapped.

After this graph: this quantifies label sensitivity on a shared source shape, rather than measuring reconstruction against ground truth.